"""empty message

Revision ID: fce0085c3a4d
Revises: 2c8d986aa9f4
Create Date: 2016-12-20 15:54:53.477738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce0085c3a4d'
down_revision = '2c8d986aa9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_notes_search_vector', 'notes', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_search_vector', table_name='notes')
    # ### end Alembic commands ###
